export const cards = [
  {
    id: "1234",
    cardMask: "476500******9641",
    accountNumber: "888804462946",
    cardNumber: "4765000604119641",
    availableBalance: 2204.0,
    holdBalance: 0.0,
    currencyName: "usd",
    backOfficeStatus: "Forced PIN change",
    status: "Valid card",
    statusCode: "0",
    statusName: "VALID CARD",
    state: "Personalization_required",
    availableStatuses: [
      {
        statusCode: "Deactivate",
        name: "Deactivate",
      },
      {
        statusCode: "ReportLostOrStolen",
        name: "Report Lost Stolen",
      },
      {
        statusCode: "SetPin",
        name: "Set Pin",
      },
      {
        statusCode: "CloseCard",
        name: "Close Card",
      },
      {
        statusCode: "ForcePinChange",
        name: "Force Pin Change",
      },
    ],
    cardholderName: "LINKCARD MDPAUTO01",
    expirationDate: "11.2026",
    expirDate: "11.2026",
    seqNumber: "1",
    nickname: null,
  },
  {
    id: "1235",
    cardMask: "476500******2450",
    accountNumber: "79095000349",
    cardNumber: "4765000473302450",
    availableBalance: 1951.0,
    holdBalance: 0.0,
    currencyName: "usd",
    backOfficeStatus: "Forced PIN change",
    status: "Valid card",
    statusCode: "0",
    statusName: "VALID CARD",
    state: "Personalization_required",
    availableStatuses: [
      {
        statusCode: "Deactivate",
        name: "Deactivate",
      },
      {
        statusCode: "ReportLostOrStolen",
        name: "Report Lost Stolen",
      },
      {
        statusCode: "Set Pin",
        name: "Set Pin",
      },
      {
        statusCode: "CloseCard",
        name: "Close Card",
      },
      {
        statusCode: "ForcePinChange",
        name: "Force Pin Change",
      },
    ],
    cardholderName: "LINKCARD MDPAUTO01",
    expirationDate: "11.2026",
    expirDate: "11.2026",
    seqNumber: "1",
    nickname: null,
  },
  {
    id: "1236",
    cardMask: "476500******2436",
    accountNumber: "79096000349",
    cardNumber: "4765000090402436",
    availableBalance: 1676.0,
    holdBalance: 0.0,
    currencyName: "usd",
    backOfficeStatus: "Forced PIN change",
    status: "Valid card",
    statusCode: "0",
    statusName: "VALID CARD",
    state: "Personalization_required",
    availableStatuses: [
      {
        statusCode: "Deactivate",
        name: "Deactivate",
      },
      {
        statusCode: "ReportLostOrStolen",
        name: "Report Lost Stolen",
      },
      {
        statusCode: "Set Pin",
        name: "Set Pin",
      },
      {
        statusCode: "CloseCard",
        name: "Close Card",
      },
      {
        statusCode: "ForcePinChange",
        name: "Force Pin Change",
      },
    ],
    cardholderName: "LINKCARD MDPAUTO01",
    expirationDate: "11.2026",
    expirDate: "11.2026",
    seqNumber: "1",
    nickname: null,
  },
  {
    id: "1237",
    cardMask: "476500******0588",
    accountNumber: "79097000349",
    cardNumber: "4765000494340588",
    availableBalance: 3671.0,
    holdBalance: 0.0,
    currencyName: "usd",
    backOfficeStatus: "Forced PIN change",
    status: "Valid card",
    statusCode: "0",
    statusName: "VALID CARD",
    state: "Personalization_required",
    availableStatuses: [
      {
        statusCode: "Deactivate",
        name: "Deactivate",
      },
      {
        statusCode: "ReportLostOrStolen",
        name: "Report Lost Stolen",
      },
      {
        statusCode: "Set Pin",
        name: "Set Pin",
      },
      {
        statusCode: "CloseCard",
        name: "Close Card",
      },
      {
        statusCode: "ForcePinChange",
        name: "Force Pin Change",
      },
    ],
    cardholderName: "LINKCARD MDPAUTO01",
    expirationDate: "11.2026",
    expirDate: "11.2026",
    seqNumber: "1",
    nickname: null,
  },
  {
    id: "1238",
    cardMask: "476500******8329",
    accountNumber: "79098000349",
    cardNumber: "4765000432288329",
    availableBalance: 3350.0,
    holdBalance: 0.0,
    currencyName: "usd",
    backOfficeStatus: "Forced PIN change",
    status: "Valid card",
    statusCode: "0",
    statusName: "VALID CARD",
    state: "Personalization_required",
    availableStatuses: [
      {
        statusCode: "Deactivate",
        name: "Deactivate",
      },
      {
        statusCode: "ReportLostOrStolen",
        name: "Report Lost Stolen",
      },
      {
        statusCode: "Set Pin",
        name: "Set Pin",
      },
      {
        statusCode: "CloseCard",
        name: "Close Card",
      },
      {
        statusCode: "ForcePinChange",
        name: "Force Pin Change",
      },
    ],
    cardholderName: "LINKCARD MDPAUTO01",
    expirationDate: "11.2026",
    expirDate: "11.2026",
    seqNumber: "1",
    nickname: null,
  },
  {
    id: "1239",
    cardMask: "476500******4806",
    accountNumber: "79099000349",
    cardNumber: "4765000672104806",
    availableBalance: 0.0,
    holdBalance: 0.0,
    currencyName: "usd",
    backOfficeStatus: "Forced PIN change",
    status: "Stolen card",
    statusCode: "7",
    statusName: "STOLEN CARD, CAPTURE",
    state: "Personalization_required",
    availableStatuses: [
      {
        statusCode: "ForcePinChange",
        name: "Force Pin Change",
      },
      {
        statusCode: "CloseCard",
        name: "Close Card",
      },
      {
        statusCode: "Activate",
        name: "Activate",
      },
      {
        statusCode: "Deactivate",
        name: "Deactivate",
      },
      {
        statusCode: "Set Pin",
        name: "Set Pin",
      },
    ],
    cardholderName: "LINKCARD MDPAUTO01",
    expirationDate: "11.2026",
    expirDate: "11.2026",
    seqNumber: "1",
    nickname: null,
  },
  {
    id: "1240",
    cardMask: "476500******6199",
    accountNumber: "79011000349",
    cardNumber: "4765000461726199",
    availableBalance: 2105.0,
    holdBalance: 0.0,
    currencyName: "usd",
    backOfficeStatus: "Forced PIN change",
    status: "Valid card",
    statusCode: "0",
    statusName: "VALID CARD",
    state: "Personalization_required",
    availableStatuses: [
      {
        statusCode: "Deactivate",
        name: "Deactivate",
      },
      {
        statusCode: "ReportLostOrStolen",
        name: "Report Lost Stolen",
      },
      {
        statusCode: "Set Pin",
        name: "Set Pin",
      },
      {
        statusCode: "CloseCard",
        name: "Close Card",
      },
      {
        statusCode: "ForcePinChange",
        name: "Force Pin Change",
      },
    ],
    cardholderName: "LINKCARD MDPAUTO01",
    expirationDate: "11.2026",
    expirDate: "11.2026",
    seqNumber: "1",
    nickname: null,
  },
];
